### ISSUE TITLE
GeographyPointJsonConverter with nulls

### ISSUE THREAD

**Issue by m1dst** [nkovacic/AzureSearchToolkit#2]
If the schema includes a GeographyPoint which isn't populated and therefore is null then an exception is thrown.

> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'location'.     at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)     at AzureSearchToolkit.Json.GeographyPointJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

Not all items in my search index are geotagged and I suspect others may have the same scenario.

Would be great to see this fixed with a nuget update.

**Comment by nkovacic** [comment]
Fixed in [0.6.1](https://www.nuget.org/packages/AzureSearchToolkit/0.6.1)
