### ISSUE TITLE
Concatenating Expressions?

### ISSUE THREAD

**Issue by m1dst** [nkovacic/AzureSearchToolkit#3]
I am trying to find a way to pass an IQueryable expression that I pre-generated into the toolkit somehow or use the concat function to merge the expression in.  Is this possible?  If it is, could you provide some pointers in the documentation?

Thanks

**Comment by nkovacic** [comment]
This would be very difficult to achieve in the current release. Currently this feature its scheduled to be included in the 0.7 release (end of the week).

**Comment by m1dst** [comment]
Great to hear!  I can work around for a little.

**Comment by MedAnd** [comment]
Hi @nkovacic, also wondering if I would be able to use your library for user generated / dynamic queries which are not known at compile time? Thx.

**Comment by nkovacic** [comment]
It still in the works, there are some delays because of other projects.

**Comment by MedAnd** [comment]
Completely understandable @nkovacic... once your latest changes land though, do you think it will be possible to support run-time / dynamic queries? Also any rough eta.. days, weeks or longer? Thx.

**Comment by nkovacic** [comment]
Currently it will support IQueriable argument for Query method on AzureSearchContext. With this you could make a dynamic query which would replace the default empty query that is currently implemented.

**Comment by nkovacic** [comment]
Will try to implement the feature this week,  0.7.0 release had priority the previous week.

**Comment by nkovacic** [comment]
@m1dst @MedAnd  I have created [DynamicTests](https://github.com/nkovacic/AzureSearchToolkit/blob/ae533d4d129ca7d1def91c9f652620dd499ddb7d/AzureSearchToolkit.IntegrationTest/Tests/DynamicTests.cs) integration test class to showcase dynamic query generation.

Additional help can be found on https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries

In later releases of AzureSearchToolkit there will be support for to pass Expression<Func<TEntity, bool>> arguments to Query<TEntity> method but not full IQueriable arguments.

**Comment by nkovacic** [comment]
Closing this issue for now. Will reopen if new unsolved use cases emerge.
